"""Added cascade between bookshelf bookshelfAssociation

Revision ID: 3912c5ef2e33
Revises: 3a28a58f1ee1
Create Date: 2025-03-25 20:37:06.887552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3912c5ef2e33'
down_revision: Union[str, None] = '3a28a58f1ee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bookAssociations_bookshelfId_fkey', 'bookAssociations', type_='foreignkey')
    op.create_foreign_key(None, 'bookAssociations', 'bookshelves', ['bookshelfId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookAssociations', type_='foreignkey')
    op.create_foreign_key('bookAssociations_bookshelfId_fkey', 'bookAssociations', 'bookshelves', ['bookshelfId'], ['id'])
    # ### end Alembic commands ###
