"""Initial migration

Revision ID: 4018c7c0411c
Revises: 
Create Date: 2025-03-22 18:14:54.411960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4018c7c0411c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookshelves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookshelves_id'), 'bookshelves', ['id'], unique=False)
    op.create_table('book_associations',
    sa.Column('bookshelfId', sa.Integer(), nullable=False),
    sa.Column('bookId', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bookshelfId'], ['bookshelves.id'], ),
    sa.PrimaryKeyConstraint('bookshelfId', 'bookId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_associations')
    op.drop_index(op.f('ix_bookshelves_id'), table_name='bookshelves')
    op.drop_table('bookshelves')
    # ### end Alembic commands ###
