"""Ratings added

Revision ID: 6a3186b12dac
Revises: 4018c7c0411c
Create Date: 2025-03-25 15:14:34.276495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a3186b12dac'
down_revision: Union[str, None] = '4018c7c0411c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userRatings',
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('bookId', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('userId', 'bookId')
    )
    op.create_index(op.f('ix_userRatings_bookId'), 'userRatings', ['bookId'], unique=False)
    op.create_index(op.f('ix_userRatings_userId'), 'userRatings', ['userId'], unique=False)
    op.create_table('bookAssociations',
    sa.Column('bookshelfId', sa.Integer(), nullable=False),
    sa.Column('bookId', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bookshelfId'], ['bookshelves.id'], ),
    sa.PrimaryKeyConstraint('bookshelfId', 'bookId')
    )
    op.drop_table('book_associations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_associations',
    sa.Column('bookshelfId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bookId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bookshelfId'], ['bookshelves.id'], name='book_associations_bookshelfId_fkey'),
    sa.PrimaryKeyConstraint('bookshelfId', 'bookId', name='book_associations_pkey')
    )
    op.drop_table('bookAssociations')
    op.drop_index(op.f('ix_userRatings_userId'), table_name='userRatings')
    op.drop_index(op.f('ix_userRatings_bookId'), table_name='userRatings')
    op.drop_table('userRatings')
    # ### end Alembic commands ###
