"""Added reviews

Revision ID: ba8f05b38482
Revises: 6a3186b12dac
Create Date: 2025-03-25 15:43:27.905785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba8f05b38482'
down_revision: Union[str, None] = '6a3186b12dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('bookId', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('userId', 'bookId')
    )
    op.create_index(op.f('ix_reviews_bookId'), 'reviews', ['bookId'], unique=False)
    op.create_index(op.f('ix_reviews_userId'), 'reviews', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_userId'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_bookId'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
