"""Added reviews

Revision ID: fdf4d8694b7c
Revises: ba8f05b38482
Create Date: 2025-03-25 15:49:36.272730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdf4d8694b7c'
down_revision: Union[str, None] = 'ba8f05b38482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('bookId', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_bookId'), 'reviews', ['bookId'], unique=False)
    op.create_index(op.f('ix_reviews_userId'), 'reviews', ['userId'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.alter_column('reviews', 'bookId',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('reviews', 'userId',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('reviews', 'id')
    # ### end Alembic commands ###
